/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZeroDaysRouteImport } from './routes/zero-days'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as AboutRouteImport } from './routes/about'
import { Route as EcosystemRouteImport } from './routes/$ecosystem'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZeroDayIdRouteImport } from './routes/zero-day.$id'
import { Route as EcosystemSlugRouteImport } from './routes/$ecosystem_.$slug'

const ZeroDaysRoute = ZeroDaysRouteImport.update({
  id: '/zero-days',
  path: '/zero-days',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/$ecosystem',
  path: '/$ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroDayIdRoute = ZeroDayIdRouteImport.update({
  id: '/zero-day/$id',
  path: '/zero-day/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemSlugRoute = EcosystemSlugRouteImport.update({
  id: '/$ecosystem_/$slug',
  path: '/$ecosystem/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$ecosystem': typeof EcosystemRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/zero-days': typeof ZeroDaysRoute
  '/$ecosystem/$slug': typeof EcosystemSlugRoute
  '/zero-day/$id': typeof ZeroDayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$ecosystem': typeof EcosystemRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/zero-days': typeof ZeroDaysRoute
  '/$ecosystem/$slug': typeof EcosystemSlugRoute
  '/zero-day/$id': typeof ZeroDayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$ecosystem': typeof EcosystemRoute
  '/about': typeof AboutRoute
  '/methodology': typeof MethodologyRoute
  '/zero-days': typeof ZeroDaysRoute
  '/$ecosystem_/$slug': typeof EcosystemSlugRoute
  '/zero-day/$id': typeof ZeroDayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$ecosystem'
    | '/about'
    | '/methodology'
    | '/zero-days'
    | '/$ecosystem/$slug'
    | '/zero-day/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$ecosystem'
    | '/about'
    | '/methodology'
    | '/zero-days'
    | '/$ecosystem/$slug'
    | '/zero-day/$id'
  id:
    | '__root__'
    | '/'
    | '/$ecosystem'
    | '/about'
    | '/methodology'
    | '/zero-days'
    | '/$ecosystem_/$slug'
    | '/zero-day/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcosystemRoute: typeof EcosystemRoute
  AboutRoute: typeof AboutRoute
  MethodologyRoute: typeof MethodologyRoute
  ZeroDaysRoute: typeof ZeroDaysRoute
  EcosystemSlugRoute: typeof EcosystemSlugRoute
  ZeroDayIdRoute: typeof ZeroDayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zero-days': {
      id: '/zero-days'
      path: '/zero-days'
      fullPath: '/zero-days'
      preLoaderRoute: typeof ZeroDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$ecosystem': {
      id: '/$ecosystem'
      path: '/$ecosystem'
      fullPath: '/$ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero-day/$id': {
      id: '/zero-day/$id'
      path: '/zero-day/$id'
      fullPath: '/zero-day/$id'
      preLoaderRoute: typeof ZeroDayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$ecosystem_/$slug': {
      id: '/$ecosystem_/$slug'
      path: '/$ecosystem/$slug'
      fullPath: '/$ecosystem/$slug'
      preLoaderRoute: typeof EcosystemSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcosystemRoute: EcosystemRoute,
  AboutRoute: AboutRoute,
  MethodologyRoute: MethodologyRoute,
  ZeroDaysRoute: ZeroDaysRoute,
  EcosystemSlugRoute: EcosystemSlugRoute,
  ZeroDayIdRoute: ZeroDayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
